import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { poppins } from "@/fonts";
import { Navbar } from "@/components/navbar/Navbar";
import { SecondaryNavbar } from "@/components/secondary_navbar/SecondaryNavbar";
// import { relative } from "path";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar/> 
        <SecondaryNavbar/>
        {children}
      </body>
    </html>
  );
}
